config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "cards#index"

  resources :cards do
    member do
      post :like  # /cards/2/like
    end

    collection do
      get :import  # /cards/import
      get :search  # /cards/search
    end

    resources :comments, shallow: true,
               except: [:index, :show, :new]
  end

  # resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  has_one_attached :photo

  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
  belongs_to :user

  has_many :favorite_cards
  has_many :users, through: :favorite_cards

  def favorited_by?(user)
    users.include?(user)
  end

  def self.search(keyword)
    where("title like '%#{keyword}%' or content like '%#{keyword}%'")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
  validates :content, presence: true

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end
end

app/models/favorite_card.rb
class FavoriteCard < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cards

  has_many :favorite_cards
  has_many :like_cards, through: :favorite_cards, source: 'card'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private
  def not_found
    render file: "public/404.html", layout: false, status: 404
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_my_card, only: [:edit, :update, :destroy]

  def search
    keyword = params[:keyword]
    @cards = Card.search(keyword).page(params[:page]).per(3)
  end

  def import
    # 匯入！
    # JOB!
    TenlongJob.set(wait: 5.seconds).perform_later(current_user)

    redirect_to root_path, notice: "卡片已匯入"
  end

  def index
    @cards = Card.page(params[:page]).per(10).order(id: :desc)
  end

  def show
    @card = Card.find(params["id"])
    @comment = Comment.new
    @comments = @card.comments.order(id: :desc)
  end

  def like
    card = Card.find(params[:id])
    if current_user.like_cards.include?(card)
      current_user.like_cards.delete(card)
      render json: { status: 0 }
    else
      current_user.like_cards << card
      render json: { status: 1 }
    end
  end

  def new
    @card = Card.new
  end

  def create
    # @card = Card.new(card_params)
    @card = current_user.cards.new(card_params)

    if @card.save
      # flash[:notice] = "新增卡片成功"
      redirect_to "/", notice: "新增卡片成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to "/", notice: '卡片更新成功'
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to "/", notice: '卡片已刪除'
  end

  private
  def card_params
    params.require(:card).permit(:title, :content, :photo)
  end

  def find_my_card
    @card = current_user.cards.find(params["id"])
    # @card = Card.find_by(id: params["id"], user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @card = Card.find(params[:card_id])
    @comment = @card.comments.new(comment_params)

    if @comment.save
      # redirect_to @card
      # app/views/comments/create.js.erb
    else
      render 'cards/show'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comment.card
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cards/_form.html.erb
<% if card.errors.any? %>
  <ul>
  <% card.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(card) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <%= f.submit %>
<% end %>

app/views/cards/edit.html.erb
<h1>編輯卡片</h1>

<%= render 'form', card: @card %>

app/views/cards/index.html.erb
<h1>卡片列表</h1>
<%= link_to "新增卡片", new_card_path %>
<hr>

<form action="/cards/search" method="get">
  <input type="text" name="keyword">
  <button type="submit">搜尋</button>
</form>

<%= paginate @cards %>

<% @cards.each do |card| %>
  <div class="card">
    <header class="card-title">
      <%= link_to card.title, card %>
      <%= link_to "編輯", edit_card_path(card) %>
      <%= link_to "刪除", card, method: :delete, data: { confirm: '確定刪除?' } %>
    </header>

    <div class="card-body">
      <p><%= card.content %></p>
      <%= image_tag card.photo.variant(resize_to_limit: [200, 200])  if card.photo.attached? %>
    </div>
  </div>
<% end %>

app/views/cards/new.html.erb
<h1>新增卡片</h1>

<%= render 'form', card: @card %>

app/views/cards/search.html.erb
<h1>卡片列表</h1>
<%= link_to "新增卡片", new_card_path %>
<hr>

<form action="/cards/search" method="get">
  <input type="text" name="keyword">
  <button type="submit">搜尋</button>
</form>

<%= paginate @cards %>

<% @cards.each do |card| %>
  <div class="card">
    <header class="card-title">
      <%= link_to card.title, card %>
      <%= link_to "編輯", edit_card_path(card) %>
      <%= link_to "刪除", card, method: :delete, data: { confirm: '確定刪除?' } %>
    </header>

    <div class="card-body">
      <p><%= card.content %></p>
    </div>
  </div>
<% end %>

app/views/cards/show.html.erb
<h1 data-controller="icon" data-icon-card-id="<%= @card.id %>">
  <%= @card.title %>
  <a data-action="icon#like" href="#" class="like_btn">
    <% if @card.favorited_by?(current_user) %>
      <i data-icon-target="thumb" class="fas fa-thumbs-up"></i>
    <% else %>
      <i data-icon-target="thumb" class="far fa-thumbs-up"></i>
    <% end %>
  </a>
</h1>

<p>
  <%= @card.content %>
</p>
<hr>
<%= form_with(model: @comment, url: card_comments_path(@card)) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

<ul class="comments">
  <%= render @comments %>
</ul>

app/views/comments/_comment.html.erb
<li>
  <%= link_to "刪除", comment, method: 'delete', data: {confirm: '確定刪除?'} %>
  <%= comment.content %>
</li>

app/views/comments/create.js.erb
var comments = document.querySelector('.comments')
comments.innerHTML = "<%= j render 'comments/comment', comment: @comment %>" + comments.innerHTML
document.querySelector('#comment_content').value = ''

app/views/common/_navbar.html.erb
<% if user_signed_in? %>
  <%= current_user.email %>
  <%= link_to '登出', destroy_user_session_path, method: 'delete'	%>
  <%= link_to '匯入', import_cards_path %>
<% else %>
  <%= link_to '註冊', new_user_registration_path %>
  <%= link_to '登入', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/navbar' %>
    <p><%= notice %></p>
    <%= yield %>
    <%= yield :bottom_js %>
  </body>
</html>